version: '3.7'
services:
  web:
    build: backend/
    command: gunicorn Ugra_hackaton.wsgi:application --bind 0.0.0.0:8005
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8005:8005
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  postgres_data:
