# Generated by Django 3.1.3 on 2020-11-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_checkpoint_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='dddd', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
