# Generated by Django 3.1.3 on 2020-11-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20201128_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.game'),
        ),
        migrations.DeleteModel(
            name='Game_in_progress',
        ),
    ]
