# Generated by Django 3.1.3 on 2020-11-29 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_invitationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='back.game'),
        ),
        migrations.CreateModel(
            name='CurrentCheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.checkpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.team')),
            ],
        ),
    ]
