# Generated by Django 3.1.3 on 2020-11-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20201129_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='next_checkpoint_id',
            new_name='next_checkpoint',
        ),
    ]
