# Generated by Django 3.1.3 on 2020-11-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20201129_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='back.game'),
            preserve_default=False,
        ),
    ]
