# Generated by Django 3.1.3 on 2020-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_checkpoint_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=3),
            preserve_default=False,
        ),
    ]
