# Generated by Django 3.1.3 on 2020-11-29 05:53

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_game_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='image',
            field=models.ImageField(default='mt.img', upload_to=back.models.get_check_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='media/img.png', upload_to=back.models.get_game_path),
            preserve_default=False,
        ),
    ]
